# Guarneri-style device YAML configuration

# Objects only available at APS

#apstools.devices.ApsMachineParametersDevice:
common_9id.devices.patched_aps.PatchedApsMachineParametersDevice:
  - name: aps
